CREATE TABLE feature_depart (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id BIGINT NOT NULL,
    depart_id  BIGINT NOT NULL,
    UNIQUE (feature_id, depart_id),
    FOREIGN KEY (feature_id) REFERENCES feature(id),
    FOREIGN KEY (depart_id)  REFERENCES depart(id)  ON DELETE CASCADE
);