CREATE TABLE process_code_type_embedding (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_code_type_id    BIGINT NOT NULL UNIQUE REFERENCES process_code_type(id) ON DELETE CASCADE,
    embedding               vector(768)
);