CREATE TABLE complaint_embedding (
     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     complaint_id   BIGINT NOT NULL UNIQUE REFERENCES complaint(id) ON DELETE CASCADE,
     embedding      vector(768)
);