CREATE TABLE file (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      file_name     VARCHAR(100)    NOT NULL,
      row_count     INT,
      capacity      BIGINT,
      uploaded_at   TIMESTAMP       NOT NULL,
      status        VARCHAR(10)     NOT NULL,
      error_message TEXT
);