CREATE TABLE feature (
     id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     content   VARCHAR(255) NOT NULL,
     depart_id BIGINT       NOT NULL,
     FOREIGN KEY (depart_id) REFERENCES depart(id)
);