CREATE TABLE complaint (
       id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       title          VARCHAR(60)     NOT NULL,
       content        VARCHAR(2000)   NOT NULL,
       code           SMALLINT,
       is_checked     BOOLEAN         NOT NULL DEFAULT FALSE,
       status         VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
       failure_reason VARCHAR(100),
       file_id        BIGINT          NOT NULL,
       depart_id      BIGINT,
       FOREIGN KEY (file_id) REFERENCES file(id),
       FOREIGN KEY (depart_id) REFERENCES depart(id)
);